name: "Bug report \U0001F41E"
description: File a bug report
labels:
  - "bug"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to do X, and Y happened instead.
  - type: textarea
    attributes: 
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...'
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected Y to happen.
  - type: textarea
    attributes:
      label: Environment
      description: Describe the environment in which the bug occurred
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
  - type: textarea
    attributes:
      label: Other information
      description: Add any other context about the problem here.
