name: "Feature request \U0001F680"
description: Suggest an idea
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: I would like to see X.
  - type: textarea
    attributes:
      label: Example
      description: An example of how this feature would be used.
      placeholder: |
        This feature would be used like this:
        ...
  - type: textarea
    attributes:
      label: Motivation
      description: Why are we doing this? What use cases does it support? What is the expected outcome?
      placeholder: |
        This feature would be useful for X.
        It would allow us to do Y.
